desktop/horae/homepage/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'$', views.index, name='index')
]

desktop/horae/horae/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from os import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^schedules/', include('schedules.urls', namespace='schedules')),
    url(r'^$', include('homepage.urls', namespace='homepage')),
    url(r'^admin/', include(admin.site.urls)),  
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

desktop/horae/schedules/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^my/$', views.my_schedule, name='my_schedule'),
	url(r'^request_cover/(\d+)/$', views.request_cover, name='request_cover'),
	url(r'^cover_shift/(\d+)/$', views.cover_shift, name='cover_shift'),
]

desktop/horae/homepage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

desktop/horae/schedules/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Company(models.Model):
	name = models.CharField(max_length=64)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Company'
		verbose_name_plural = 'Companies'


class Employee(models.Model):
	user = models.OneToOneField(User)
	company = models.ForeignKey(Company)

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = 'Employee'


class AssignedShift(models.Model):
	_DAY_CHOICES = (
		('Monday', 'Monday'),
		('Tuesday', 'Tuesday'),
		('Wednesday', 'Wednesday'),
		('Thursday', 'Thursday'),
		('Friday', 'Friday'),
		('Saturday', 'Saturday'),
		('Sunday', 'Sunday')
	)
	
	day = models.CharField(max_length=10, choices=_DAY_CHOICES)
	start_time = models.TimeField()
	end_time = models.TimeField()
	employee = models.ForeignKey(Employee)
	cover_requested = models.BooleanField(default=False)

	def __str__(self):
		return '{0}, {1}-{2} ({3})'.format(
			self.day,
			self.start_time, 
			self.end_time, 
			self.employee.user.username
		)

	class Meta:
		verbose_name = 'Shift'


class PreferredShift(models.Model):
	_DAY_CHOICES = (
		('Monday', 'Monday'),
		('Tuesday', 'Tuesday'),
		('Wednesday', 'Wednesday'),
		('Thursday', 'Thursday'),
		('Friday', 'Friday'),
		('Saturday', 'Saturday'),
		('Sunday', 'Sunday')
	)
	
	day = models.CharField(max_length=10, choices=_DAY_CHOICES)
	start_time = models.TimeField()
	end_time = models.TimeField()
	employee = models.ForeignKey(Employee)

	def __str__(self):
		return '{0}, {1}-{2} ({3})'.format(
			self.day,
			self.start_time, 
			self.end_time, 
			self.employee.user.username
		)

	class Meta:
		verbose_name = 'Preferred Time'

desktop/horae/homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

desktop/horae/schedules/views.py
from django.shortcuts import render
from .models import *
from django.core.mail.message import EmailMessage

def index(request):
	return render(request, 'schedules/index.html')

def my_schedule(request):
	context = {
		'monday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Monday'
			).order_by('start_time'),
		'tuesday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Tuesday'
			).order_by('start_time'),
		'wednesday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Wednesday'
			).order_by('start_time'),
		'thursday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Thursday'
			).order_by('start_time'),
		'friday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Friday'
			).order_by('start_time'),
		'saturday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Saturday'
			).order_by('start_time'),
		'sunday': AssignedShift.objects.filter(
				employee__user=request.user,
				day='Sunday'
			).order_by('start_time'),
	}
	return render(request, 'schedules/my_schedule.html', context=context)

def request_cover(request, shift_id):
	shift = AssignedShift.objects.get(id=shift_id)
	shift.cover_requested = True
	shift.save()
	employee_list = []
	for user in User.objects.filter(employee__company=request.user.employee.company):
		if not (AssignedShift.objects.filter(
				start_time__range=(shift.start_time, shift.end_time)
			) | AssignedShift.objects.filter(
				end_time__range=(shift.start_time, shift.end_time)
			)
		).filter(day=shift.day, employee=user.employee):
			employee_list.append(user.email.encode('utf-8'))
	body = 'Shift: {0}, {1}-{2} ({3})\n'.format(
		shift.day, 
		shift.start_time,
		shift.end_time,
		shift.employee.user.email
	)
	body += 'To cover: 192.168.1.135:8080/schedules/cover/{0}/'.format(shift_id)
	EmailMessage(
		to=employee_list,
		cc=[request.user.email],
		from_email='auxo@horae.com',
		subject='AUXO: Your coworker has requested a shift be covered',
		body=body
	).send()
	return render(request, 'schedules/request_cover.html')

def cover_shift(request, shift_id):
	shift = AssignedShift.objects.get(id=shift_id)
	if shift.cover_requested:
		shift.cover_requested = False
		shift.employee = request.user.employee
		shift.save()
		return render(request, 'schedules/cover_shift.html')
	else:
		return render(request, 'schedules/shift_covered.html')

desktop/horae/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Horae</title>

    <!-- Bootstrap core CSS -->
    <link href={% static "css/bootstrap.css" %} rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href={% static "css/ie10-viewport-bug-workaround.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src={% static "js/ie-emulation-modes-warning.js" %}></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <b><a class="navbar-brand" href="{% url 'homepage:index' %}">Horae</a></b>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <a class="navbar-brand" href="{% url 'schedules:index' %}">Scheduling</a>
          <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    <br>
    <br>
    <br>

    <!-- Main jumbotron for a primary marketing message or call to action -->
{% block jumbotron %}
    <div class="jumbotron">
      <div class="container">
        <h1>Horae</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2015 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
{% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src={% static "js/vendor/jquery.min.js" %}><\/script>')</script>
    <script src={% static "js/bootstrap.js" %}></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src={% static "js/ie10-viewport-bug-workaround.js" %}></script>
  </body>
</html>

desktop/horae/templates/homepage/index.html
{% extends "base.html" %}

desktop/horae/templates/schedules/cover_shift.html
{% extends "base.html" %}

{% block jumbotron %}
{% endblock %}

{% block content %}
	<h2>You have covered this shift.</h2>
{% endblock %}

desktop/horae/templates/schedules/index.html
{% extends "base.html" %}
{% block jumbotron %}
{% endblock %}
{% block content %}
	<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2><a href="{% url 'schedules:my_schedule' %}">My Schedule</a></h2>
        </div>
        <div class="col-md-4">
          <h2>Add</h2>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2015 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
{% endblock %}

desktop/horae/templates/schedules/my_schedule.html
{% extends "base.html" %}

{% block jumbotron %}
{% endblock %}

{% block content %}
	<h1>My Shifts:</h1>
	<ul>
		{% for shift in monday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in tuesday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in wednesday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in thursday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in friday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in saturday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
		{% for shift in sunday %}
			<li>{{shift.day}}, {{shift.start_time}}-{{shift.end_time}}
			<a href="{% url 'schedules:request_cover' shift.id %}">Request someone cover this shift</a></li>
		{% endfor %}
	</ul>
{% endblock %}

desktop/horae/templates/schedules/request_cover.html
{% extends "base.html" %}

{% block jumbotron %}
{% endblock %}

{% block content %}
	<h2>Your request has been sent to your coworkers. You can cancel this at Schedules > Covering Shifts</h2>
{% endblock %}

desktop/horae/templates/schedules/shift_covered.html
{% extends "base.html" %}

{% block jumbotron %}
{% endblock %}

{% block content %}
	<h2>This shift has already been covered.</h2>
{% endblock %}